### PR TITLE
Move to trash action

### LINKED ISSUE #210: Add support for DEL-key
Hey @jurplel,
could you add support for DEL-key, please?

It would be helpful for fast clean up of useless pictures after a photo shooting.

best regards

### LINKED ISSUE #344: Better read errors
Add file name to error message, show a blank image, and allow the user to continue to the next image. Investigate including svg errors for invalid svg files (they all just show "unknown error")
- [x] Add file name to error message
- [x] Show a blank image (and allow the user to continue to the next image [this will be made possible with code that will make deleting possible so should be done after])
- [x] Svg errors

### LINKED ISSUE #387: Modal error dialog interrupts image browsing
**Environment:**
- OS: macOS 11.1 Big Sur
- qView version: 4.0

**Information:**
I have a folder containing images of a variety of formats, including jpg, gif and png, and also a macOS alias to a png image in another directory. When I use the arrow keys to browse through images, I get the following when qView gets to the alias:

Screen Shot 2021-02-01 at 1 48 55 PM

I can press `OK` and than reverse direction, but cannot continue in the original direction past the alias, much less open it.

It would be more graceful if qView either silently ignored files it could not open or simply displayed the above error message not as a dialog but in the original browse window (as a proxy for the image it could not open) and allow one to take note and proceed with browsing.

### LINKED ISSUE #388: allow deletion (and silent deletion) of images as they are being browsed
A common use of image viewers is to efficiently sift through a collection of images to cull out the unwanted ones. Most image viewers have a `Delete` command in the file menu and also a keyboard shortcut, often `⌘⌫` to avoid accidental deletions.

I'd recommend `⌫` produces a confirmation dialog and `⌘⌫` deletes silently, with the user of course able to change this behavior in qView's Shortcuts Preferences.

### LINKED ISSUE #425: "Rename" operation general improvements and macOS compliance
# All OS

## Rename dialog: The initial text selection should be the filename without the dot and fileextension
qView renaming dialog initial text selection

As a general UX recommendation regarding renaming this is the most efficient selection for renaming:
- Just type to overwrite entirely.
- Arrow-right then type to add to the end.
- Arrow-left then type to add to the beginning.
- Overwriting the suffix is the exception. It's still possible, but takes some more keystrokes. Appropriate for rarer use cases.

# macOS

## Default shortcut for "Rename…" currently is F2
- F-keys at all and their standardization reflects 1987 [IBM Common User Access](https://en.wikipedia.org/wiki/IBM_Common_User_Access) still conventional on Windows and many Linux distros.
- But the Mac never made use of them, instead used more mnemonic alphabetical key-bindings as CMD-S for "Save" etc.
- In Finder renaming is bound to ENTER. Was once CMD-Enter. Still commonplace in some 3rd party apps.
- I recommend CMD-ENTER, as renaming is not the main use case in an image viewer, preserving ENTER for more frequently used functions such as toggling fullscreen or entering an edit mode (as in Apple Photos) and SPACE for play/pause (currently "P" in qView, that's ok)

## Implement the default macOS window bar renaming dialog
as an additional macOS standard compliant means for renaming, see screenshot:
qView renaming dialog as all native apps

### PR DESCRIPTION
**Pull request by jurplel**
Resolves #387; Resolves #344; Resolves #210; Resolves #425; Resolves #388

Test out this build here and provide feedback!
https://dev.azure.com/jurplel/qView/_build/results?buildId=877&view=artifacts&pathAsName=false&type=publishedArtifacts

### CODE REVIEW

**Comment by jkananen** [comment]
Thanks, keen on trying. What's the difference between `macos` and `macosx` builds?

**Comment by cyclism6486** [comment]
Trying out the macos build (on macOS 10.15.7) and the delete function seems to be working well.  I had to change the shortcut to be just the delete key (instead of Cmd-Del and the two other defaults) on my MacBook Pro to improve my workflow.  One suggestion for when people change a shortcut - instead of deleting everything else in the shortcut box, keep the defaults (allowing the user to delete or change them if they want, but at least you don't have to recreate everything) - I hope that makes sense.  Looks like a great job on the ability to delete during image viewing though!

**Comment by jurplel** [comment]
@jkananen macosx builds are for 10.10+ instead of 10.13+

@cyclism6486 Thanks for trying it out, that is a good suggestion about the shortcuts but I am going to leave it for now and stay focused.

**Comment by jkananen** [comment]
Deleting works, thank you very much. I'm also happy with the default shortcut cmd + backspace.

This will be my final farewell to Xee!

**Comment by svekl** [comment]
Tried macos build on Big Sur, delete works like a charm. But having some issues with "next/previous" image, sometimes  pressing key does nothing on screen, but pressing second time scrolls through two images

**Comment by jurplel** [comment]
@svekl Thanks for the info, I think you are right on that

**Comment by vassudanagunta** [comment]
The fix for #388 is good. Thank you!

But the handling of errors is not so good. Please see my new (and original) comment under #387.

**Comment by porg** [comment]
I tested the build in regards to #425 and it qualifies for a reopening.

**Comment by Scobee** [comment]
@jurplel I can't see any artifact in the link you provided in the top post. Can you provide another link / place to download a dmg for osx ?
Thank you!

**Pull request merged**
