### PR TITLE
Set as desktop background action

### PR DESCRIPTION
**Pull request by sonulohani**
Supports only for windows.

Issue: https://github.com/jurplel/qView/issues/309

### CODE REVIEW

**Comment by sonulohani** [comment]
I have placed the action above **Full screen** action. In menu bar I have put the action under **View** menu. Please let me know your opinion.

**Comment by sonulohani** [comment]
There is a build failure with the error "mainwindow.obj : error LNK2019: unresolved external symbol __imp_SystemParametersInfoW referenced in function "public: void __cdecl MainWindow::setAsDesktopBackground(void)" (?setAsDesktopBackground@MainWindow@@QEAAXXZ)" which is very strange because in my machine I am able to compile it successfully. I will look into this matter later. If you know any solution please let me know.

**Comment by jurplel** [comment]
Don't know why that might be happening. Check MSVC versions and included libraries perhaps.

**Comment by sonulohani** [comment]
Now the build is green. Please see the below screenshot for action positioning in menu. 
Context menu positioning
Menu positioning in menubar

If you're okay with the changes please merge the PR.
Thanks

**Comment by sonulohani** [comment]
I dont have linux os so can't develop, however if you're going to make changes related to linux this is the link for reference:- https://gitlab.com/luspi/photoqt/blob/master/cplusplus/scripts/getanddostuff/wallpaper.cpp#L49

**Comment by sonulohani** [comment]
Hi @jurplel 

Do you have any plan on reviewing this PR.

**Comment by jurplel** [comment]
Hi, sorry for the lack of communication. I have already reviewed it but I'm not ready to get into making this feature yet. What I will do is put it on a feature branch.

**Pull request merged**
