### PR TITLE
Color space support

### PR DESCRIPTION
**Pull request by jdpurcell**
Adds support for color space conversion (#283), allowing the user to pick from the following options:
Screenshot 2023-01-15 at 5 44 44 PM

~~As nice it would be to auto-detect the monitor's ICC profile, I don't plan on implementing that myself. Nonetheless, I think even just this first step would be appreciated by a lot of users.~~

### CODE REVIEW

**Comment by Andreas0602** [comment]
This basic color space support is not sufficient. Auto-detecting the monitor's ICC profile is not just "nice", it's a must-have feature.

**Comment by soren121** [comment]
@Andreas0602 Would you like to implement that then? This is an open-source project, please be courteous to the people contributing their free time.

**Comment by Andreas0602** [comment]
I didn't want to upset anyone. But on the substance, I stand by my criticism. An image viewer that inaccurately reproduces colors is useless for any serious purpose. It would be great if this issue would be solved properly.

**Comment by jurplel** [comment]
Honestly the route might be to go full littleCMS

**Comment by jdpurcell** [comment]
I figured out how to detect the ICC profile on Windows/macOS without too much trouble, so I just added the "Auto-detect" option. It should detect the ICC profile of the monitor on which qView is placed when initially opening an image. It does not redo color space conversion for the current image if qView is moved to a different monitor, but it will use the new monitor's ICC profile for future images it opens that aren't cached/preloaded already.

**Comment by jdpurcell** [comment]
My latest commits enable auto-detect by default and improve the caching situation, i.e. whenever an image is loaded it will detect if the monitor's color space is different and invalidate the cache. Automated build failure is related to #563.

**Comment by jdpurcell** [comment]
@jurplel Latest commit implements ICC profile detection on Linux.

**Comment by jurplel** [comment]
Thank you!

**Pull request merged**
