### PR TITLE
Adding information in fullscreen

### PR DESCRIPTION
**Pull request by Lightjohn**
I just added a label to show what would be the name of the main window in fullscreen.

I'm not sure I put the right call in the right place but the idea is here and it seems to work in all cases:

* Starting as fullscreen
* Enabling/disabling in preferences 

Also to not add too much code, if there no text it will show an empty label (small white line at the top) not sure if it's acceptable for you (in fact I tried, but did not manage to do it).

### CODE REVIEW

**Comment by jurplel** [comment]
Failing CI on windows

**Comment by Lightjohn** [comment]
Fixed, strange difference between gcc and msvc

**Comment by jurplel** [comment]
## Some notes for either of us

Issues I am currently experiencing with this implementation:
- I am getting an issue sometimes with light text on a light background (linux, gnome3, adwaitadark) 
image
- It doesn't seem to be vertically centered either (note that it is way at the top)

I like your implementation!

**Comment by Lightjohn** [comment]
I have the same issue under Linux but the fix is very easy: set the stylesheet to  `QLabel { color : black; }` make things readable to me.

Not being vertically centered was my intention, if it's on the side I can ignore it unless I want the information.
Should I add the center?

**Comment by jurplel** [comment]
I mean the text vertically centered within the label. I am thinking that using a stylesheet would cause other breakages with dark themes. I'll see what I can do.

**Comment by jurplel** [comment]
How's that looking?

**Comment by jurplel** [comment]
Adwaita-Dark
image
Fusion
image

Okay, I see inconsistent margins now

**Comment by Lightjohn** [comment]
To be fair it looks pretty nice!
With nearly no change in the code.

Not sure to see the issue with margins on the screenshot

**Comment by jurplel** [comment]
I think I fixed it pretty well now. The margins will copy that of the menubar. I just need to test on windows and mac and make sure everything is looking ok over there.

**Comment by jurplel** [comment]
macOS didn't have a sizehint for that so I added a default margin when there is no sizehint. It is looking pretty decent now on all platforms.

**Comment by jurplel** [comment]
:rocket:

**Pull request merged**
