### PR TITLE
Add support for apng format

### PR DESCRIPTION
**Pull request by sonulohani**

### CODE REVIEW

**Comment by jurplel** [comment]
I have found a solution that allows pngs to be read as apng without subclassing qimagereader. I can't see any issues with this approach. Your solution for reading the frames tests perfectly and I have not found any compatibility regressions. Pretty much ready to merge unless you have any other suggestions. Great work.

**Comment by sonulohani** [comment]
Hi @jurplel 

I have removed redundant call to setFileName. Please re-review and if everything is fine then please merge the PR. Your solution looks good. Tested with animated-png with png as extension and its working as expected.

**Comment by jurplel** [comment]
Yes there will need to be two changes in distribution--Linux packages should add an optional dependency if available, and builds (which are becoming automated for the first time next version) should have it included. In addition, I will make a webpage that shows the format support for each operating system and explains which are dependent on plugins.

**Comment by sonulohani** [comment]
Hi @jurplel 
Are you gonna merge this PR. 

Regards,
Sonu

**Comment by jurplel** [comment]
For some reason I hesitated to begin with but I can't see any reason not to merge now.

**Pull request merged**
